version : "3.9"

services:

  web:
    container_name: webapp
    build:
      context: ./webapphr/
    env_file:
      - ".env"
    ports:
      - 3000:3000

  # db:
  #   container_name: DB
  #   image : mysql
  #   env_file:
  #     - ".env"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - 3306:3306