version: "3.3"

services:
  my_db:
    container_name: mytestdb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    ports:
      -3306:3306
  web:
    container_name: webapp_container
    build:
      context: ./webapphr
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - my_db
  